# Generated by Django 2.2.4 on 2022-10-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdjango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='you a bitch', max_length=500)),
                ('artist', models.CharField(default='you a bitch', max_length=500)),
            ],
        ),
    ]
