# Generated by Django 2.2.4 on 2022-10-30 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstdjango', '0003_auto_20221030_0814'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Records',
        ),
    ]
